"""empty message

Revision ID: 578f4fb674e8
Revises: 1b78ca49cafb
Create Date: 2019-08-14 12:52:04.904937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578f4fb674e8'
down_revision = '1b78ca49cafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('todos', sa.Column('token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'token')
    op.drop_column('todos', 'active')
    # ### end Alembic commands ###
